var waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){var timerId=uniqueId?uniqueId:"Don't call this twice without a uniqueId";if(timers[timerId]){clearTimeout(timers[timerId]);}
timers[timerId]=setTimeout(callback,ms);};})();$(document).ready(function(){$("input[name='js_enabled'], input[name='javascript_enabled']").val('1');$('.mobile-menu-toggle').on('touchstart, click',function(event){event.preventDefault();var mobileMenu=$('.mobile-menu');mobileMenu.toggleClass('open');function openMenu(){mobileMenu.animate({right:'0px',},150);$('.overlay').fadeIn(150);$('body').addClass('no-scroll');}
function closeMenu(){mobileMenu.animate({right:'-1000px',},150);$('.overlay').fadeOut(150);$('body').removeClass('no-scroll');$('.mm-accordion ul').slideUp();$('.mm-accordion button').removeClass('active');}
if(mobileMenu.hasClass('open')){openMenu();}else{closeMenu();}
$('.overlay').click(function(){closeMenu();mobileMenu.removeClass('open');});});$('.mm-accordion ul').hide();$('.mm-accordion button').click(function(){$(this).next().slideToggle();$(this).toggleClass('active');});function compressSidebar(){while($('.sidebar').height()>=$('#main-content').height()){var $boxes=$('.sidebar-box');$boxes.sort(function(a,b){var aPri=$(a).attr('data-box-priority');aPri=aPri?aPri:0;var bPri=$(b).attr('data-box-priority');bPri=bPri?bPri:0;if(aPri>bPri){return 1;}else if(aPri<bPri){return-1;}
return 0;});var $removalCandidate=$boxes.last();if(!($removalCandidate)||!($removalCandidate.attr('data-box-priority')>0)){break;}
$removalCandidate.remove();}}
compressSidebar();setTimeout(compressSidebar,500);var menuBreakpoint=816;var mediumBreakpoint=1024;var Dropdown=function(id,topics){this.topics=topics;this.menuDropdownBar=$(id+'.menu-bar');this.navItemWrapper=$(id+'.top-nav-dropdown-item');this.navItemTrigger=$(id+'.top-nav-dropdown-item a');};var clickDropdown=function(val){var clicked=navArray[val];clicked.navItemTrigger.on('click',function(event){event.preventDefault();if(search.hasClass('js-search-show')){hideSearch();if(window.innerWidth>=mediumBreakpoint){if($(window).scrollTop()<=$('header').offset().top){showMenuBar(0);}}}
if(!clicked.menuDropdownBar.hasClass('js-menu-bar-hide')){hideMenuBar(val);}else{for(var i=0;i<navArray.length;i++){var item=navArray[i];if(!item.menuDropdownBar.hasClass('js-menu-bar-hide')){if(item.topics){if((window.innerWidth<mediumBreakpoint)||($(window).scrollTop()>$('header').offset().top)){hideMenuBar(i);}}else{hideMenuBar(i);}}}
showMenuBar(val);}});};var navArray=[];var topics=new Dropdown('.topics',true);navArray.push(topics);for(var i=0;i<navArray.length;i++){clickDropdown(i);}
var showMenuBar=function(index){navArray[index].menuDropdownBar.removeClass('js-menu-bar-hide');navArray[index].menuDropdownBar.addClass('js-menu-bar-transition');navArray[index].navItemWrapper.addClass('js-top-nav-item-active');};var hideMenuBar=function(index){navArray[index].menuDropdownBar.addClass('js-menu-bar-hide');navArray[index].menuDropdownBar.removeClass('js-menu-bar-transition');navArray[index].navItemWrapper.removeClass('js-top-nav-item-active');};var showNavItem=function(index){navArray[index].navItemWrapper.addClass('js-top-nav-item-visible');};var hideNavItem=function(index){navArray[index].navItemWrapper.removeClass('js-top-nav-item-visible');};var search=$('.menu-search');var siteMenu=$('.site-menu');function displaySearch(){search.removeClass('js-search-hide');search.addClass('js-search-show');$('#search').focus();$('.search-overlay').fadeIn(150);$('body').addClass('no-scroll');}
function hideSearch(){search.addClass('js-search-hide');search.removeClass('js-search-show');$('.search-overlay').fadeOut(150);$('body').removeClass('no-scroll');}
function searchFixed(){search.css('position','fixed');}
function searchUnfixed(){search.css('position','absolute');}
function menuFixed(){siteMenu.addClass('js-site-menu-fixed');for(i=0;i<navArray.length;i++){navArray[i].menuDropdownBar.css('position','fixed');}}
function menuUnfixed(){siteMenu.removeClass('js-site-menu-fixed');for(i=0;i<navArray.length;i++){navArray[i].menuDropdownBar.css('position','absolute');}}
function updateMenuAppearance(){for(i=0;i<navArray.length;i++){var item=navArray[i];if(!item.topics){showNavItem(i);}}
if($('header').length){if($(window).scrollTop()<=$('header').offset().top){menuUnfixed();searchUnfixed();if((window.innerWidth<mediumBreakpoint)&&(window.innerWidth>=menuBreakpoint)){showNavItem(0);for(i=0;i<navArray.length;i++){hideMenuBar(i);}}else{hideNavItem(0);showMenuBar(0);}}else{menuFixed();searchFixed();showNavItem(0);for(i=0;i<navArray.length;i++){hideMenuBar(i);}
if(window.innerWidth>=menuBreakpoint){navArray[0].menuDropdownBar.show();}}}
for(i=0;i<navArray.length;i++){if(navArray[i].menuDropdownBar.length!==0){if((window.innerWidth<mediumBreakpoint)&&(window.innerWidth>=menuBreakpoint)){navArray[i].menuDropdownBar.css('left',(parseInt(navArray[i].navItemWrapper.offset().left,10)+'px'));}else if(window.innerWidth>=mediumBreakpoint){navArray[i].menuDropdownBar.css('left','0px');}}}}
$(document).ready(updateMenuAppearance);$(window).scroll(updateMenuAppearance);$(window).resize(updateMenuAppearance);$('.search-toggle, .menu-search .close, .search-overlay').on('click',function(event){event.preventDefault();if(search.hasClass('js-search-show')){hideSearch();}else{if((!siteMenu.hasClass('js-site-menu-fixed'))&&(window.innerWidth>mediumBreakpoint)){showMenuBar(0);for(i=1;i<navArray.length;i++){hideMenuBar(i);}}else{for(i=0;i<navArray.length;i++){hideMenuBar(i);}}
displaySearch();}});$('.menu-search .close').on('click',function(){hideSearch();});if(window.location.pathname==='/dashboard/admin/'){$(document).ready(function(){menuUnfixed();showMenuBar(0);hideNavItem(0);});$(window).scroll(function(){menuUnfixed();showMenuBar(0);hideNavItem(0);});$(window).resize(function(){menuUnfixed();showMenuBar(0);hideNavItem(0);});}
$('.signup .js-email-input input, .inline-signup .js-email-input input').on('click, focus',function(){var thisCheckboxList=$(this).parents('form').find('.signup-list');var checkboxListChildren=thisCheckboxList.children();var numberOfCheckboxes=checkboxListChildren.length;if(numberOfCheckboxes>1){thisCheckboxList.slideDown('500');}});$('.js-form-email-validate').submit(function(event){var value=$(this).find('input[type=email]').val();if(!value||value.indexOf('@')<0||value.indexOf('.')<0){event.preventDefault();$(this).find('.form-error__message').remove();$(this).find('input[type=email]').addClass('form-error__highlight');$(this).find('.email-input').append("<p class='form-error__message'>Please enter a valid email.</p>");return false;}
return true;});$('.inline-signup form').attr('target','_blank');$('.inline-signup .js-form-email-validate').submit(function(){var value=$(this).find('input[type=email]').val();if(value||value.indexOf('@')>0||value.indexOf('.')>0){$('.inline-signup p, .inline-signup .email-input, .inline-signup .signup-list, .inline-signup .button').hide();$('.inline-signup form').append('<p>Thanks! Look out for an email from us soon.</p>');}});if(!('placeholder'in document.createElement('input'))){$('span.screen-reader-text').removeClass('screen-reader-text').addClass('screen-reader-text-visible');}
$('.message__close').click(function(){var thisMessage=$(this).closest('.message');$(thisMessage).fadeOut('fast');});$('.site-alert__close').click(function(){var cookieString='_id_site_notification='+$(this).attr('data-notification-id')+
';expires='+$(this).attr('data-notification-expires')+';path=/';document.cookie=cookieString;$('.site-alert').hide();});if($('body').hasClass('not-first-page')){$('.js-search-accordion .js-search-accordion-inner').hide();$('.js-search-accordion .js-search-accordion-toggle').click(function(){$('.js-search-accordion .js-search-accordion-inner').slideToggle();$(this).toggleClass('js-search-active');});}else{$('div.js-search-accordion').removeClass('js-search-accordion');}
function clearIcon(inputBox){var inputWrapper=$(inputBox).closest('.search-input');var inputClear=$(inputWrapper).find('.search-input__clear');var inputValue=$(inputBox).val();if(inputValue!==null&&inputValue!==''){$(inputClear).show();}else{$(inputClear).hide();}}
$('.search-input__clear').click(function(){$(this).parent().find('input').val('');$(this).hide();});clearIcon($('.search-input').find('input'));$('.search-input').find('input').keyup(function(){clearIcon($(this));});});