(function($){var prestitialAds={daysBetweenPrestitial:7,defaultTimeoutSeconds:15,testing:function(){if(document.location.search.indexOf('prestitial_test')!==-1){return true;}
return false;},testingNoAd:function(){if(this.testing()===true&&document.location.search.indexOf('no_ad')!==-1){return true;}
return false;},overrideTimeout:function(){if(this.testing()===true&&document.location.search.match('no_timeout')!==null){return true;}
return false;},timeoutSeconds:function(){return this.defaultTimeoutSeconds*1000;},setPrestitialPossibleCookie:function(){if(document.cookie.indexOf('_prestitialPossible')===-1){if(typeof mixpanel!=='undefined'){var sampleSize=10;if(Math.floor(Math.random()*sampleSize)+1===1){mixpanel.track('prestitial possible',{'sample_size':sampleSize,'url':window.location.href.replace(/[\?\#].*$/,''),});}}
this.setCookie('_prestitialPossible',Date.now(),this.daysBetweenPrestitial);}},setCookie:function(cName,value,expireDays){var exdate=new Date();exdate.setDate(exdate.getDate()+expireDays);document.cookie=cName+'='+encodeURIComponent(value)
+((expireDays==null)?'':';expires='+exdate.toUTCString())
+'; path=/';},screenMeetsSizeReqs:function(){var windowWide=$(window).innerWidth()>640;var windowHigh=$(window).innerHeight()>640;return(windowWide&&windowHigh);},userIsPrestitialEligible:function(){return((document.cookie.indexOf('_prestitialViewed')===-1)&&(window.location.href.indexOf('?prestitial_skip')===-1));},pageIsPrestitialEligible:function(){if(this.testing()===true){return true;}
if(this.screenMeetsSizeReqs()===true&&this.userIsPrestitialEligible()===true){return true;}
return false;},logClosePrestitialAdBy:function(closedBy){if((typeof mixpanel!=='undefined')){mixpanel.track('prestitial closed',{'closed_by':closedBy,'url':window.location.href.replace(/[\?\#].*$/,''),});}},initialize:function(daysBetweenPrestitial){$('body').css('overflow','hidden');$('div#prestitial-init').show();if(typeof daysBetweenPrestitial==='undefined'){this.daysBetweenPrestitial=7;}else{this.daysBetweenPrestitial=daysBetweenPrestitial;}
var closeFunc=this.logClosePrestitialAdBy;var hideFunc=this.closePrestitial;$('#prestitial-outer').show().click(function(e){closeFunc('user');hideFunc();});},closePrestitial:function(){$('body').css('overflow','');$('div#prestitial-init').hide();$('#prestitial-outer').hide();},prestitialAdIsClosed:function(){return($('#prestitial-outer').is(':hidden')===true&&$('div#prestitial-init').is(':hidden')===true);},};window.prestitialAds=prestitialAds;})(jQuery);