define(['jquery','megamenu','localization/copy'],function($,menuNav,copy){var pelm={};menuNav.init();$(function(){require(['util/eventhandler'],function(_event){_event.windowfocus(function(){$('body').addClass('focused').removeClass('blurred');});_event.windowblur(function(){$('body').removeClass('focused').addClass('blurred');});})
if(window.pelm_util.browser.isIE9()){$('html').addClass('ie9');}
$(document).ready(function(){if($("span.shareCounter").length!=0){var targetDiv=[{tag:"fb-share",selector:'div',nextSelector:'a',ajaxUrl:window.url_countrycode+"/api/social/getfbcnt",cntContainer:'span',cntClass:'shareCounter'},{tag:"twitter-share",selector:'div',nextSelector:'a',ajaxUrl:window.url_countrycode+"/api/social/gettweetcnt",cntContainer:'span',cntClass:'shareCounter'},{tag:"gplus-share",selector:'div',nextSelector:'a',ajaxUrl:window.url_countrycode+"/api/social/getgpluscnt",cntContainer:'span',cntClass:'gplus-count'},{tag:"pin-it-button",selector:'a',nextSelector:'',ajaxUrl:window.url_countrycode+"/api/social/getpincnt",cntContainer:'span',cntClass:'shareCounter'}];$(targetDiv).each(function(i,el){var dataUrl=$(el.selector+"."+el.tag+" "+el.nextSelector).attr('data-url');if(dataUrl){$.ajax({url:el.ajaxUrl,data:{dataurl:dataUrl},success:function(count){$(el.selector+"."+el.tag+" "+el.cntContainer+"."+el.cntClass).text(count);},error:function(){}});}});}});window.autocomplete_hover=false;var suggestion_lists=$(".recent_list_div,.map_suggestion_list,.presenters-list,.sugg_list_airport_div");suggestion_lists.hover(function(){window.autocomplete_hover=true;},function(){window.autocomplete_hover=false;var el=$(this);setTimeout(function(){if(window.autocomplete_hover==false){if(el.hasClass('map_suggestion_list')){el.addClass('off');}else{el.hide();}}},1500);});window.autocomplete_hover_suggestion=false;var suggestion_lists_main=$(".suggestion_list_div,.suggestion_list_news_div"),suggestion_list_timeout=null;suggestion_lists_main.hover(function(){window.autocomplete_hover_suggestion=true;},function(){window.autocomplete_hover_suggestion=false;var el=$(this);if(suggestion_list_timeout!=null){clearTimeout(suggestion_list_timeout);}
suggestion_list_timeout=setTimeout(function(){if(window.autocomplete_hover_suggestion==false){el.hide();if(el.hasClass('.suggestion_list_div')){$('#suggestionlist').attr('class','suggestion_list');}
suggestion_list_timeout=null;}},2500);});;var rmc=0,rmAd=function(){var l=document.getElementById('leaderboard'),s=null;if(l){s=l.getElementsByTagName('style');if(s){for(var i=s.length-1;i>=0;i--){if(typeof s[i].innerHTML!=='undefined'&&s[i].innerHTML){try{s[i].innerHTML='';}catch(ex){}}};window._q.remove(rmAd);}}else{window._q.remove(rmAd);};rmc++;if(rmc==15){window._q.remove(rmAd);}};window._q.add(rmAd,1);jQuery(document).ready(function(){jQuery('.twitter-selector').click(function(){if(!jQuery(this).hasClass('active')){jQuery('.presenters-list').show();jQuery(this).addClass('active');}else{jQuery('.presenters-list').hide();jQuery(this).removeClass('active');}
return false;});});(function($){$.fn.twitterCheckbox=function(){return this.each(function(){var checkbox=$(this);if(checkbox.data("val")!=null)return;checkbox.addClass("twitterOpaque");checkbox.data('val',this.checked);var aElem=$('<span class="twitterCheckboxElem"></span>');checkbox.wrap('<span class="twitterCheckbox"></span>').parent().prepend(aElem);this.checked&&aElem.addClass('Checked');checkbox.on("change",function()
{if(this.checked){$('.presenters-list .Checked').removeClass('Checked');aElem.addClass('Checked');}});});};$.fn.csUpdate=function()
{$(':radio',this).twitterCheckbox();};})(jQuery);$(function(){if($(".presenters-list").length&&$.isFunction($.fn.csUpdate)){$(".presenters-list").csUpdate();}});function fireCustomEvent(obj,evt){var fireOnThis=obj;if(document.createEvent){var evObj=document.createEvent('Events');evObj.initEvent(evt,true,true);fireOnThis.dispatchEvent(evObj);}
else if(document.createEventObject){var event;event=document.createEventObject();event.eventType='mouseout';fireOnThis.fireEvent('on'+event.eventType,event);}}
var delayedResources=(function(){var self=this,debug=false;self.images=function(){var elms=document.getElementsByTagName('img'),i=0,elm=null,attr='',dc=0,debug=false;if(elms.length){for(i=elms.length-1;i>=0;i--){elm=elms[i];attr=elm.getAttribute('data-img');if(attr){dc++;if(self.inView(elm)){if(debug){console.log('attr'+i);console.log(elm);console.log(attr);}
elm.setAttribute('src',attr);elm.removeAttribute('data-img');elm.setAttribute('data-customevent','1');fireCustomEvent(elm,'onimageload');}}}}
return elms.length;}
self.inView=function(elem){var height=document.documentElement.clientHeight,rects=elem.getClientRects(),v=false,on_top=function(r){var x=(r.left+r.right)/2,y=(r.top+r.bottom)/2;return document.elementFromPoint(x,y)===elem||document.elementFromPoint(r.left,r.top)===elem||document.elementFromPoint(r.right,r.top)===elem||document.elementFromPoint(x,r.top+10)===elem;};for(var i=0,l=rects.length;i<l;i++){var r=rects[i],in_viewport=false;in_viewport=r.top>0?r.top<=height:(r.bottom>0&&r.bottom<=height);if(in_viewport&&on_top(r)){v=true;break;}}
return v;}
return self;})();window._q.add(delayedResources.images,1);$('.default-value').each(function(){var defaultValue=this.value;$(this).focus(function(){if(this.value==defaultValue){this.value='';}});$(this).blur(function(){if(this.value==''){this.value=defaultValue;}});});var _prof=(function(){var u=window.placecode,p='';if(typeof window._uf!="undefined"&&typeof window._uf.u!="undefined"){u=window._uf.u;}
if(typeof window.postalcode!='undefined'&&window.postalcode){p+='/'+window.postalcode;if(typeof window.gridindex!="undefined"&&window.gridindex){p+='/'+window.gridindex;}}
return function(index,el){if($(this).parents('.trend-tabs').length){el.href=el.href+p;}else{el.href=el.href+u+p;}
el.ref=el.ref+u+p;};})();$('a[data-profile]').each(_prof);var searchXhr,searchThrottle,list,countryCodes;if(!String.prototype.trim){String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,'');};}
window.mainSearchMore=function(cls){$('#suggestionlist').attr('class','suggestion_list '+cls);$('#suggestionlist_news').attr('class','suggestion_list_news '+cls);}
window.mainSearchLess=function(cls){$('#suggestionlist').removeClass(cls);$('#suggestionlist_news').removeClass(cls);}
window.indexSearchMore=function(cls){$('#more-'+cls).addClass('hidden');$('#less-'+cls).removeClass('hidden');$('.more-search-list-'+cls).removeClass('hidden');}
window.indexSearchLess=function(cls){$('#more-'+cls).removeClass('hidden');$('#less-'+cls).addClass('hidden');$('.more-search-list-'+cls).addClass('hidden');}
$(function(){if($('html').hasClass('lt-ie10')){$("#search").val(copy.search.label_loc_keyword);}});$("#search, #search_news").on('focus',function(){if($('html').hasClass('lt-ie10')&&$(this).val()==copy.search.label_loc_keyword){$(this).val('');}}).on('blur',function(){if($('html').hasClass('lt-ie10')&&$(this).val()==''){$(this).val(copy.search.label_loc_keyword);}}).on('keyup',function(e){var kCode=e.which||e.keyCode;var formid=$(this).attr('id');var retrylimit;if(typeof window._config.newsearch!='undefined'&&typeof window._config.newsearch.retry_limit!='undefined'){retrylimit=window._config.newsearch.retry_limit;}else{retrylimit=1;}
if($(this).val().length>=3){countryCodes=window._config.search_country_code_null;if(formid=='search_news'){$(".suggestion_list_news_div").show();}else{$(".suggestion_list_div").show();}
var searchText=$(this).val().trim();if(searchThrottle){clearTimeout(searchThrottle);}
if(typeof searchXhr!="undefined"){searchXhr.abort();}
if(kCode==40||kCode==38||kCode==37||kCode==39){return;}
searchThrottle=setTimeout(function(){var d_lat,d_lng;if((typeof window._user_config!="undefined")&&(typeof window._user_config=="object")&&(typeof window._user_config.lat!="undefined")&&(typeof window._user_config.lng!="undefined")){d_lat=parseFloat(window._user_config.lat).toFixed(4);d_lng=parseFloat(window._user_config.lng).toFixed(4);}else if((typeof window._config.lat!="undefined")&&(typeof window._config.lng!="undefined")){d_lat=parseFloat(window._config.lat).toFixed(4);d_lng=parseFloat(window._config.lng).toFixed(4);}
searchXhr=$.ajax({url:(window.user_countrycode_url?window.user_countrycode_url:window.url_countrycode)+'/api/location/search',dataType:'json',data:{"searchText":searchText,"countryCodes":countryCodes,"lat":d_lat,"long":d_lng},timeout:5000,tryCount:0,retryLimit:retrylimit,success:function(data){$('.suggestion_list').html('');var typeKey={'city':['location','locations',0,''],'province':['location','locations',0,''],'country':['location','locations',0,''],'ski':['location','ski',0,''],'school':['school','schools',0,''],'schools':['school','schools',0,''],'golf':['golf','golf',0,''],'airport':['airport','airports',0,''],'airports':['airport','airports',0,''],'park':['park','parks',0,''],'parks':['park','parks',0,''],'cottage':['cottage','cottage',0,''],'campground':['campground','campground',0,''],'beach':['beach','beach',0,''],'marine':['marine','marine',0,''],'attraction':['attraction','attractions',0,''],'attractions':['attraction','attractions',0,''],'postcode':['location','locations',0,''],'school':['school','schools',0,''],'schools':['school','schools',0,''],'airport':['airport','airports',0,''],'park':['park','parks',0,''],'postcode':['location','locations',0,'']};var text='<li class="pointcast-message"><img src="'+window._config.image_url+'PointCast-Logo-White-'+window._config.lang.toLowerCase()+'.png" alt="POINTCAST"><p>'+copy.search.pointcastlbl+'</p></li>';if(data!=''&&data!=null){var foundCity=0,foundSki=0,foundSchools=0,foundGolf=0,foundAirports=0,foundParks=0,typeCtr=0,moreClass='more';$.each(data,function(k,v){var itemClass='result',val='',text_sub='',text_items='';if(typeKey[v.type]){if(typeKey[v.type][2]==0){typeKey[v.type][2]+=1;typeCtr=0;}}
typeCtr++;if(typeKey[v.type]){typeKey[v.type][2]+=1;if(typeCtr<20){if(typeCtr>5){itemClass+=' '+moreClass
if(typeKey[v.type]){itemClass+=' '+moreClass+'_'+typeKey[v.type][1];}}
val=v.name;if(v.type=="province"){val=v.name+", "+v.country;}else{if(v.countrycode==window._config.domain_countrycode&&(v.countrycode=='CA')||(v.countrycode=='US')){if(v.provcode){val=v.name+", "+v.provcode;}else if(v.province){val=v.name+", "+v.province;}}else{if(v.province){val=v.name+", "+v.country;}
if((window._config.locale.substring(3)).toUpperCase()=='CA'&&v.provcode){val=v.name+", "+v.provcode;}else if(v.province){val=v.name+", "+v.province;if(typeof v.displayCountry=='undefined'&&(v.countrycode!='CA')&&(v.countrycode!='US')){val=v.name+", "+v.country;}}
if(v.displayCountry){val=v.name;if(v.province){val=val+", "+v.province;}
val=val+", "+v.country;}}}
text_items+='<li class="'+itemClass+'"><a data-event-action="clicks" data-event-label="searchDropDown | '+searchText+'" data-omni_link_name="'+window._config.site_prefix+': search: dropdown click: '+v.code+'" data-href="'+v.url+'" data-omni_action="search: dropdown" onclick="setTimeout(function(){window.location.href = \''+v.url+'\';}, 800);" tabindex="'+k+'">'+val+'</a></li>';typeKey[v.type][3]+=text_items;}}});var more_less='';for(types in typeKey){more_less='';if(typeKey[types][2]==0){continue;}
if(typeKey[types][2]>6){more_less='<a data-omni_link_name="'+window._config.site_prefix+': search: results: show more" data-omni_action="search: results: show more/less" href="javascript:window.mainSearchMore(\'more_'+typeKey[types][1]+'\'); " class="see-more more_'+typeKey[types][1]+'">+</a><a data-omni_link_name="'+window._config.site_prefix+': search: results: show less" data-omni_action="search: results: show more/less" href="javascript:window.mainSearchLess(\'more_'+typeKey[types][1]+'\');" class="see-less more_'+typeKey[types][1]+'">-</a>';}
text+='<li class="heading '+types+'">'+more_less+copy.search[typeKey[types][1]]+'</li>'+typeKey[types][3];}}else{text+="<li class='no-result'>"+copy.search.error+"</li>";}
if(formid=='search_news'){$('.suggestion_list_news').html(text);list=$('.suggestion_list_news li');}else{$('.suggestion_list').html(text);list=$('.suggestion_list li');}},error:function(xhr,textStatus,errorThrown){if(textStatus=='timeout'){this.tryCount++;if(this.tryCount<=this.retryLimit){$.ajax(this);return;}
return;}}});},250);}else if(kCode!=40&&kCode!=38){if(formid=='search_news'){$(".suggestion_list_news_div").hide();$('.suggestion_list_news').html('');}else{$(".suggestion_list_div").hide();$('.suggestion_list').html('');}}}).on('blur',function(){$(document).on('click',function(event){if(!$(event.target).closest('.navsearchform').length&&!$(event.target).closest(".o-mainsearch-results").length){$(".suggestion_list_div").hide();$("#mylocations").hide();$('#search').val('');}});});$('#searchform','#searchform_news').submit(function(){var formid=$(this).attr('id');var query_length,num_suggestions,num_locations;query_length=$(this).length;if(formid=='search_news'){num_suggestions=$('ul#suggestionlist_news li.result').length;num_locations=$('ul#locationslist_news li.result').length;}else{num_suggestions=$('ul#suggestionlist li.result').length;num_locations=$('ul#locationslist li.result').length;}
if(window._config.locale=='en_gb'&&((query_length>0&&query_length<2)||(num_suggestions==0&&num_locations==0)))
{return false;}});$(document).on('click','#closeList',function(){$(".suggestion_list_div").hide();});$('#photoDetails, .photo-detail').find('#search-query').on("click",function(){if($("#search-query").val()==ugc_default_search_text){$("#search-query").val('');return false;}}).on("blur",function(){if($("#search-query").val()==''){$("#search-query").val(ugc_default_search_text);return false;}});$(document).ready(function(){if(typeof ugc_default_search_text!="undefined"){$('#photoDetails, .photo-detail').find('#search-query').val(ugc_default_search_text);}
if((typeof window._user_config!="undefined")&&(typeof window._user_config=="object")&&(typeof window._user_config.lat!="undefined")&&(typeof window._user_config.lng!="undefined")){$('#searchlat').val(parseFloat(window._user_config.lat).toFixed(4));$('#searchlong').val(parseFloat(window._user_config.lng).toFixed(4));$('#searchlat_news').val(parseFloat(window._user_config.lat).toFixed(4));$('#searchlong_news').val(parseFloat(window._user_config.lng).toFixed(4));}else if((typeof window._config.lat!="undefined")&&(typeof window._config.lng!="undefined")){$('#searchlat').val(parseFloat(window._config.lat).toFixed(4));$('#searchlong').val(parseFloat(window._config.lng).toFixed(4));$('#searchlat_news').val(parseFloat(window._config.lat).toFixed(4));$('#searchlong_news').val(parseFloat(window._config.lng).toFixed(4));}});$(document).on('keydown','#search, #search_news',function(e){arrowKeyEvent(e);return;});var arrowKeyEvent=function(e){var kCode=e.which||e.keyCode,c,selected;if((kCode!=40&&kCode!=38&&kCode!=13&&kCode!=39&&kCode!=37)||typeof list=='undefined'){return;}
selected=list.filter('.selected');if(!(kCode==39||kCode==37))
{list.removeClass('selected');list.removeClass('headingselected');}
if(kCode==40){if(!selected.length||selected.is(':last-child')){c=list.eq(2);}else{c=selected.next();}}else if(kCode==38){if(!selected.length||selected.is(':nth-child(2)')){c=list.last();}else{c=selected.prev();}}else if(kCode==13){if(selected.length>0){e.preventDefault();if(selected.find('a:first').hasClass('see-more')||selected.find('a:first').hasClass('see-less'))
{return false;}
dataLayer.push({'event':"eventTracker",'eventCategory':window._config.ga_product,'eventAction':'clicks','eventLabel':"searchEnter | "+$("#search").val()});var href=selected.find('a').attr('data-href');window.location.href=href;return false;}}
else if(kCode==37){if(!selected.find('a:first').hasClass('see-more'))
{return false;}
if(selected.length>0){e.preventDefault();var classList=selected.find('a:first').attr('class').split(' ');for(i=0;i<classList.length;i++){if(classList[i].indexOf("more_")!==-1){window.mainSearchLess(classList[i]);}}
return false;}}
else if(kCode==39){if(!selected.find('a:first').hasClass('see-more'))
{return false;}
if(selected.length>0){e.preventDefault();var classList=selected.find('a:first').attr('class').split(' ');for(i=0;i<classList.length;i++){if(classList[i].indexOf("more_")!==-1){window.mainSearchMore(classList[i]);}}
return false;}}
c.addClass('selected');if(c.hasClass("heading")){if(c.find('a:first').length)
{c.addClass('headingselected');}
else
{return arrowKeyEvent(e);}
return;}
if(c.hasClass('more')&&!c.is(":visible")){return arrowKeyEvent(e);}};function isValidPostalCodeZipCode(postalCode){var postalCodeRegexUS=/^([0-9]{5})$/;var postalCodeRegexCA=/^([A-Za-z][0-9][A-Za-z])\s*$/;var postalCodeRegexFullCA=/^([A-Za-z][0-9][A-Za-z][0-9][A-Za-z][0-9])\s*$/;var postalCodeRegexFullWithSpaceCA=/^([A-Za-z][0-9][A-Za-z][\s][0-9][A-Za-z][0-9])\s*$/;if(postalCodeRegexCA.test(postalCode)||postalCodeRegexFullCA.test(postalCode)||postalCodeRegexFullWithSpaceCA.test(postalCode)||postalCodeRegexUS.test(postalCode)){if((!isNaN(postalCode)&&postalCode.length==5)||(isNaN(postalCode)&&postalCode.length==3)||(isNaN(postalCode)&&postalCode.length==6)||(isNaN(postalCode)&&postalCode.length==7)){return true;}}
return false;}
if(typeof window.pelm=="undefined"){window.pelm=function(){};}
window.pelm.track={};window.pelm.track.page=function(prod,subprod,pagename){var z=clone(s_pelm);z.prop1=prod;z.eVar1=prod;z.prop2=subprod;z.eVar2=subprod;z.pageName=pagename;if(window._config.stopOmniture==false){z.t();}};window.pelm.track.linkClick=function(eventLabel,eventAction){dataLayer.push({'event':'eventTracker','eventCategory':dataLayer[0].product,'eventAction':eventAction,'eventLabel':eventLabel});};window.pelm.track.link=function(omniStr,slinkname,eventStr,omni_delay_data,omni_href_data,omni_target_data){if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){linkvars=new Object();if(typeof omniStr!='undefined'&&omniStr!=null&&omniStr!=""&&typeof slinkname!='undefined'&&slinkname!=null&&slinkname!=""&&typeof eventStr!='undefined'&&eventStr!=null&&eventStr!=""){linkvars.linkTrackVars="eVar25,prop25,eVar39,prop39";linkvars.prop25=omniStr;linkvars.eVar25=omniStr;linkvars.prop39="event: "+eventStr;linkvars.eVar39="event: "+eventStr;if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',slinkname,linkvars);}}else if(typeof omniStr!='undefined'&&omniStr!=null&&omniStr!=""&&typeof slinkname!='undefined'&&slinkname!=null&&slinkname!=""){linkvars.linkTrackVars="eVar25,prop25";linkvars.prop25=omniStr;linkvars.eVar25=omniStr;if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',slinkname,linkvars);}}else if(typeof slinkname!='undefined'&&slinkname!=null&&slinkname!=""){if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',slinkname);}}
if(typeof omni_delay_data!='undefined'&&omni_delay_data!=''&&omni_href_data!=''&&typeof omni_target_data!='undefined'&&omni_target_data!=''){setTimeout(function(){window.open(omni_href_data,omni_target_data);},parseInt(omni_delay_data));return false;}else if(typeof omni_delay_data!='undefined'&&omni_delay_data!=''&&omni_href_data!=''){setTimeout(function(){window.location.href=omni_href_data;},parseInt(omni_delay_data));return false;}}};window.pelm.track.promo_click=function(promo_type,promo_title,traking_type){if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var promo_page=window.s_pelm.prop1;if(typeof promo_page!='undefined'&&promo_page!=null&&promo_page!="")
{promo_page=promo_page.toLowerCase().trim();if(promo_page=="home"){promo_page="home page";}else if(promo_page=="forecasts"){promo_page="city page";}else{promo_page="ros";}}
else
{promo_page="ros";}
promovars=new Object();if(typeof promo_type!='undefined'&&promo_type!=null&&promo_type!=""&&typeof promo_title!='undefined'&&promo_title!=null&&promo_title!=""&&typeof traking_type!='undefined'&&traking_type!=null&&traking_type!=""){promovars.linkTrackVars="eVar59,prop59,eVar60,prop60,eVar61,prop61,events";promovars.prop59=traking_type+": "+promo_page+": "+promo_type+": "+promo_title;promovars.eVar59=traking_type+": "+promo_page+": "+promo_type+": "+promo_title;promovars.prop61=traking_type+": "+promo_page;promovars.eVar61=traking_type+": "+promo_page;promovars.prop60=traking_type+": "+promo_type;promovars.eVar60=traking_type+": "+promo_type;promovars.linkTrackEvents="event30";promovars.events="event30";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',"promo click",promovars);}}}};window.pelm.track.promo_view=function(obj){var traking_type=typeof $(obj).attr('data-omni_traking_type')!='undefined'&&$(obj).attr('data-omni_traking_type')!=''?$(obj).attr('data-omni_traking_type'):'link';var promo_type=typeof $(obj).attr('data-omni_promo_type')!='undefined'&&$(obj).attr('data-omni_promo_type')!=''?$(obj).attr('data-omni_promo_type'):'';var promo_title=typeof $(obj).attr('data-omni_promo_title')!='undefined'&&$(obj).attr('data-omni_promo_title')!=''?$(obj).attr('data-omni_promo_title'):'';if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var promo_page=window.s_pelm.prop1;if(typeof promo_page!='undefined'&&promo_page!=null&&promo_page!="")
{promo_page=promo_page.toLowerCase().trim();if(promo_page=="home"){promo_page="home page";}else if(promo_page=="forecasts"){promo_page="city page";}else{promo_page="ros";}}
else
{promo_page="ros";}
promovars=new Object();if(typeof promo_type!='undefined'&&promo_type!=null&&promo_type!=""&&typeof promo_title!='undefined'&&promo_title!=null&&promo_title!=""&&typeof traking_type!='undefined'&&traking_type!=null&&traking_type!=""){promovars.linkTrackVars="eVar59,prop59,eVar60,prop60,eVar61,prop61,events";promovars.prop59=traking_type+": "+promo_page+": "+promo_type+": "+promo_title;promovars.eVar59=traking_type+": "+promo_page+": "+promo_type+": "+promo_title;promovars.prop61=traking_type+": "+promo_page;promovars.eVar61=traking_type+": "+promo_page;promovars.prop60=traking_type+": "+promo_type;promovars.eVar60=traking_type+": "+promo_type;promovars.linkTrackEvents="event29";promovars.events="event29";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',"promo view",promovars);}}}};window.pelm.track.promo_view_gap=function(el){var promo_obj=el.children[0];var gap_promo_type=typeof $(promo_obj).attr('data-promo_type')!='undefined'&&$(promo_obj).attr('data-promo_type')!=''?$(promo_obj).attr('data-promo_type'):'no_promo_type';var gap_promo_title=typeof $(promo_obj).attr('data-promo_title')!='undefined'&&$(promo_obj).attr('data-promo_title')!=''?$(promo_obj).attr('data-promo_title'):'no_promo_title';if(!(gap_promo_type=='no_promo_type'&&gap_promo_title=='no_promo_title')){dataLayer.push({'event':'eventTracker','eventCategory':dataLayer[0].product,'eventAction':"views",'eventLabel':gap_promo_type+' | '+gap_promo_title});}};window.pelm.track.promo_click_gap=function(el){var promo_obj=el.children[0];var gap_promo_type=typeof $(promo_obj).attr('data-promo_type')!='undefined'&&$(promo_obj).attr('data-promo_type')!=''?$(promo_obj).attr('data-promo_type'):'no_promo_type';var gap_promo_title=typeof $(promo_obj).attr('data-promo_title')!='undefined'&&$(promo_obj).attr('data-promo_title')!=''?$(promo_obj).attr('data-promo_title'):'no_promo_title';if(!(gap_promo_type=='no_promo_type'&&gap_promo_title=='no_promo_title')){dataLayer.push({'event':'eventTracker','eventCategory':dataLayer[0].product,'eventAction':"clicks",'eventLabel':gap_promo_type+' | '+gap_promo_title});}};window.pelm.track.socialShare=function(sObj){if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){smivars=new Object();smivars.linkTrackVars="prop7,prop8,prop9,prop39,eVar7,eVar8,eVar9,eVar30,eVar39,events";smivars.linkTrackEvents="event7";smivars.events="event7";smivars.prop9=sObj.title;smivars.prop7=sObj.media_category;smivars.prop8=sObj.media_type;smivars.eVar9=sObj.title;smivars.eVar7=sObj.media_category;smivars.eVar8=sObj.media_type;smivars.eVar30=sObj.share_type;smivars.eVar39="event: social media interaction";smivars.prop39="event: social media interaction";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',"Social Media Interaction",smivars);}}};$(document).on("click","a,.collapse,.expand,button",function(){if($(this).hasClass('disable-click-track')){return;}
return window.pelm.track.click(this);});window.pelm.track.click=function(obj){var omni_link_name=typeof $(obj).attr('data-omni_link_name')!='undefined'&&$(obj).attr('data-omni_link_name')!=''?$(obj).attr('data-omni_link_name'):'';var omni_action=typeof $(obj).attr('data-omni_action')!='undefined'&&$(obj).attr('data-omni_action')!=''?$(obj).attr('data-omni_action'):'';var omni_event=typeof $(obj).attr('data-omni_event')!='undefined'&&$(obj).attr('data-omni_event')!=''?$(obj).attr('data-omni_event'):'';var omni_target_data=typeof $(obj).attr('data-omni_target')!='undefined'&&$(obj).attr('data-omni_target')!=''?$(obj).attr('data-omni_target'):'';var omni_traking_type=typeof $(obj).attr('data-omni_traking_type')!='undefined'&&$(obj).attr('data-omni_traking_type')!=''?$(obj).attr('data-omni_traking_type'):'link';var omni_promo_type=typeof $(obj).attr('data-omni_promo_type')!='undefined'&&$(obj).attr('data-omni_promo_type')!=''?$(obj).attr('data-omni_promo_type'):'';var omni_promo_title=typeof $(obj).attr('data-omni_promo_title')!='undefined'&&$(obj).attr('data-omni_promo_title')!=''?$(obj).attr('data-omni_promo_title'):'';var omni_delay_data=typeof $(obj).attr('data-omni_delay')!='undefined'&&$(obj).attr('data-omni_delay')!=''?$(obj).attr('data-omni_delay'):'';var omni_href_data=typeof $(obj).attr('href')!='undefined'&&$(obj).attr('href')!=''?$(obj).attr('href'):'';if(omni_delay_data!=''&&omni_delay_data=='true'){omni_delay_data=500;}
if(omni_promo_type!=""&&omni_promo_title!=""&&omni_traking_type=="promo box"){window.pelm.track.promo_click(omni_promo_type,omni_promo_title,omni_traking_type);}else if(omni_promo_type!=""&&omni_promo_title!=""&&omni_traking_type=="sponsor"){window.pelm.track.promo_click(omni_promo_type,omni_promo_title,omni_traking_type);}else if(omni_action!=""&&omni_link_name!=""&&omni_event!=""&&omni_traking_type=="link"){window.pelm.track.link(omni_action,omni_link_name,omni_event,omni_delay_data,omni_href_data,omni_target_data);}else if(omni_action!=""&&omni_link_name!=""&&omni_traking_type=="link"){window.pelm.track.link(omni_action,omni_link_name,null,omni_delay_data,omni_href_data,omni_target_data);}else if(omni_link_name!=""&&omni_traking_type=="link"){window.pelm.track.link(null,omni_link_name,null,omni_delay_data,omni_href_data,omni_target_data);}
return true;};window.pelm.track.commenting=function(){if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var linkName="UGC Contribution";vars=new Object();vars.linkTrackVars="prop7,prop8,prop9,prop30,prop39,eVar7,eVar8,eVar9,eVar30,eVar39,events";if(jQuery("#publishToFacebook").attr("checked")!="undefined"&&jQuery("#publishToFacebook").attr("checked")==true){vars.linkTrackEvents="event7,event11";vars.events="event7,event11";linkName="Social Media Interaction";}else{vars.linkTrackEvents="event11";vars.events="event11";}
vars.eVar9=jQuery("#OmniMediaTitle").val();vars.prop9=jQuery("#OmniMediaTitle").val();vars.eVar7=jQuery("#OmniMediaCategory").val();vars.prop7=jQuery("#OmniMediaCategory").val();vars.eVar8=jQuery("#OmniMediaType").val();vars.prop8=jQuery("#OmniMediaType").val();vars.eVar30="Commenting";vars.eVar39="event: ugc contribution";vars.prop39="event: ugc contribution";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',linkName,vars);}}};window.pelm.track.headline_view=function(obj){var headline=typeof $(obj).attr('data-headline')!='undefined'&&$(obj).attr('data-headline')!=''?$(obj).attr('data-headline'):'';var headline_cat=typeof $(obj).attr('data-headline_cat')!='undefined'&&$(obj).attr('data-headline_cat')!=''?$(obj).attr('data-headline_cat'):'';var headline_page=typeof $(obj).attr('data-headline_page')!='undefined'&&$(obj).attr('data-headline_page')!=''?$(obj).attr('data-headline_page'):'';dataLayer.push({'event':'eventTracker','eventCategory':dataLayer[0].product,'eventAction':"views",'eventLabel':'headlineText | '+headline_cat+' | '+headline,'headlineViews':1});if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var linkName="Headline View";headline_cat=(headline_cat.replace(/_/g," ")).toLowerCase();headline_page=headline_page.replace(/_/g," ");vars=new Object();vars.linkTrackVars="eVar53,eVar54,eVar55,events";vars.linkTrackEvents="event28";vars.events="event28";vars.eVar53="custom banner text: "+headline_page+": "+headline_cat+": "+headline;vars.eVar54=headline_page;vars.eVar55="cbt: "+headline_cat+" headlines";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',linkName,vars);}}};window.pelm.track.headline_click=function(obj){var headline=typeof $(obj).attr('data-headline')!='undefined'&&$(obj).attr('data-headline')!=''?$(obj).attr('data-headline'):'';var headline_cat=typeof $(obj).attr('data-headline_cat')!='undefined'&&$(obj).attr('data-headline_cat')!=''?$(obj).attr('data-headline_cat'):'';var headline_page=typeof $(obj).attr('data-headline_page')!='undefined'&&$(obj).attr('data-headline_page')!=''?$(obj).attr('data-headline_page'):'';dataLayer.push({'event':'eventTracker','eventCategory':dataLayer[0].product,'eventAction':"clicks",'eventLabel':'headlineText | '+headline_cat+' | '+headline,'headlineClicks':1});if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var omni_delay_data=typeof $(obj).attr('data-omni_delay')!='undefined'&&$(obj).attr('data-omni_delay')!=''?$(obj).attr('data-omni_delay'):'';var omni_href_data=typeof $(obj).attr('href')!='undefined'&&$(obj).attr('href')!=''?$(obj).attr('href'):'';if(omni_delay_data!=''&&omni_delay_data=='true'){omni_delay_data=500;}
var linkName="Headline Click";headline_cat=(headline_cat.replace(/_/g," ")).toLowerCase();headline_page=headline_page.replace(/_/g," ");vars=new Object();vars.linkTrackVars="eVar53,eVar54,eVar55,events";vars.linkTrackEvents="event5";vars.events="event5";vars.eVar53="custom banner text: "+headline_page+": "+headline_cat+": "+headline;vars.eVar54=headline_page;vars.eVar55="cbt: "+headline_cat+" headlines";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o',linkName,vars);}
if(typeof omni_delay_data!='undefined'&&omni_delay_data!=''&&omni_href_data!=''){setTimeout(function(){window.location.href=omni_href_data;},parseInt(omni_delay_data));return false;}}};window.pelm.track.countdown_view=function(title,countdown_name,eventVar){if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var product_name=window.s_pelm.prop1;if(typeof product_name=='undefined'){product_name=window.location.pathname.split("/")[1];}
vars=new Object();vars.linkTrackVars="eVar56,eVar57,eVar58,events";vars.linkTrackEvents=eventVar;vars.events=eventVar;vars.eVar56=title+": "+countdown_name;vars.eVar57=title+": "+product_name;vars.eVar58=title+": "+"total views";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o','conutdown view',vars);}}};window.pelm.track.countdown_click=function(title,countdown_name,eventVar){if(typeof(s_pelm)!='undefined'&&window._config.stopOmniture==false){var product_name=window.s_pelm.prop1;if(typeof product_name=='undefined'){product_name=window.location.pathname.split("/")[1];}
vars=new Object();vars.linkTrackVars="eVar56,eVar57,eVar58,events";vars.linkTrackEvents=eventVar;vars.events=eventVar;vars.eVar56=title+": "+countdown_name;vars.eVar57=title+": "+product_name;vars.eVar58=title+": "+"total views";if(typeof s_pelm.tl==='function'){s_pelm.tl(this,'o','conutdown click',vars);}}};$("#nav-links").find("li").find("a").on("click",function(){var omni_nav_item=typeof $(this).attr('data-omni_nav')!='undefined'&&$(this).attr('data-omni_nav')!=''?$(this).attr('data-omni_nav'):'';if(omni_nav_item!='')
{var link_url=this.href;var omni_var="?intcmp=";if(link_url.indexOf('?')>0){omni_var="&intcmp=";}
var pos=link_url.indexOf('#');if(pos>20){this.href=link_url.substring(0,pos)+omni_var+omni_nav_item+'&'+link_url.substring(pos,link_url.length);}else{this.href=link_url+omni_var+omni_nav_item;}}});$(document).on("click","td.cal-sq",function(){window.pelm.track.link("monthly calendar: popup",window._config.site_prefix+": monthly calendar: "+window.placecode+": popup");});if(typeof window.isNitroHeader!=="undefined"&&window.isNitroHeader){require(['web/modules/woahbar'],function(woahbar){woahbar.init();});}else{var theState;var orig_toolbar_pos=null;function getCookie(key){var keyValue=document.cookie.match('(^|;) ?'+key+'=([^;]*)(;|$)');return keyValue?keyValue[2]:null;}
theState=getCookie('pelm_cstate');var stub_showing=false;window.woahbar_show=function(){if(!document.documentElement.classList.contains("unstick-toolbar")&&document.documentElement.classList.contains("takeover")&&!document.documentElement.classList.contains("alert-details-page")){orig_toolbar_pos=$('.toolbar').css("position");$('.toolbar').css({position:"static",top:"auto"});}
if(stub_showing){$('.woahbar-stub').slideUp('fast',function(){$('.woahbar-stub').slideDown('fast','linear');$('body').addClass('has_woahbar','fast','linear');$('body').animate({"marginTop":"0"},300);});function setCookie(key,value){var expires=new Date();expires.setTime(expires.getTime()+15768000000);document.cookie=key+'='+value+';path=/;expires='+expires.toUTCString();}
setCookie('pelm_cstate','open');}else{$('.woahbar').slideDown(200,'linear');$('body').addClass('has_woahbar',200,'linear');$('body').animate({"marginTop":"0"},250);$(window).scroll(function(){woahbar_hide();});}};window.woahbar_temp_hide=function(){$('.woahbar').slideUp('fast',function(){$('.woahbar-stub').slideDown(100,'linear');stub_showing=true;});$('body').removeClass('has_woahbar',100,'linear');if($(window).width()>1024){$('body').animate({"marginTop":"0"},250);stub_showing=false;}};window.woahbar_hide=function(){$('body').removeClass('has_woahbar',100,'linear');$('.woahbar').slideUp('fast',function(){$('.woahbar-stub').slideDown(100,'linear');stub_showing=true;});function setCookie(key,value){var expires=new Date();expires.setTime(expires.getTime()+15768000000);document.cookie=key+'='+value+';path=/;expires='+expires.toUTCString();}
setCookie('pelm_cstate','closed');if($(window).width()>1024){$('body').animate({"marginTop":"0"},250);}
if(!document.documentElement.classList.contains("unstick-toolbar")&&document.documentElement.classList.contains("takeover")&&!document.documentElement.classList.contains("alert-details-page")){$('.toolbar').css({position:orig_toolbar_pos,top:"4px"});}};window.showWoahBar=function(obj,effect,options,duration){if($.ui){$(obj).show(effect,options,duration);}else{require(['jquery-ui'],function(jui){if(typeof jQuery.ui==='object'){jQuery(obj).show(effect,options,duration);}});}};window.setConsentAccepted=function(key,value){document.cookie=key+'='+value+';path=/;';window.trackingConsent=true;};window.woahbar_accepted=function(){var consentDateTime=new Date().getTime();setConsentAccepted('pelm_consent',consentDateTime);require(['web/modules/my_account_lr/user'],function(user){user.save_consent(true);});woahbar_hide();};$(document).ready(function(){if($('.woahbar').length){window.setTimeout(function(){if(theState=="closed")
{woahbar_hide();}
if(theState==null||theState=="open")
{woahbar_show();}},0);}});}
$("body").on("click",".share_fb,.share_twitter,.pin_it_button,.social_share",function(e){var shareType=typeof $(this).attr('data-sharetype')!='undefined'&&$(this).attr('data-sharetype')!=''?$(this).attr('data-sharetype'):'';var url=typeof $(this).attr('data-url')!='undefined'&&$(this).attr('data-url')!=''?(typeof $(this).attr('data-fromservice')!='undefined'&&$(this).attr('data-fromservice')!=''&&$(this).attr('data-fromservice')=='microservice'?'https://'+window.location.hostname+window.location.pathname:$(this).attr('data-url')):'';var picture=typeof $(this).attr('data-picture')!='undefined'&&$(this).attr('data-picture')!=''?$(this).attr('data-picture'):'';var title=typeof $(this).attr('data-title')!='undefined'&&$(this).attr('data-title')!=''?$(this).attr('data-title'):'';var caption=typeof $(this).attr('data-caption')!='undefined'&&$(this).attr('data-caption')!=''?$(this).attr('data-caption'):'';var description=typeof $(this).attr('data-description')!='undefined'&&$(this).attr('data-description')!=''?$(this).attr('data-description'):'';var media_category=typeof $(this).attr('data-media_category')!='undefined'&&$(this).attr('data-media_category')!=''?$(this).attr('data-media_category'):'';var media_type=typeof $(this).attr('data-media_type')!='undefined'&&$(this).attr('data-media_type')!=''?$(this).attr('data-media_type'):'';var omni_link_name=typeof $(this).attr('data-omni_link_name')!='undefined'&&$(this).attr('data-omni_link_name')!=''?$(this).attr('data-omni_link_name'):'';var omni_action=typeof $(this).attr('data-omni_action')!='undefined'&&$(this).attr('data-omni_action')!=''?$(this).attr('data-omni_action'):'';var gap_label=typeof $(this).attr('data-gap-label')!='undefined'&&$(this).attr('data-gap-label')!=''?$(this).attr('data-gap-label'):'';shareVars=new Object();if(url!=""){shareVars.url=url;}
if(picture!=""){shareVars.picture=picture;}
if(gap_label!=""){shareVars.gap_label=gap_label;}
if(title!=""){shareVars.title=title;}
if(caption!=""){shareVars.caption=caption;}
if(description!=""){shareVars.description=description;}
if(media_category!=""){shareVars.media_category=media_category;}
if(media_type!=""){shareVars.media_type=media_type;}
if(omni_link_name!=""){shareVars.omni_link_name=omni_link_name;}
if(omni_action!=""){shareVars.omni_action=omni_action;}
if(shareType=="fb"){shareVars.share_type="Facebook Share";shareVars.fbkey=typeof $(this).attr('data-fbkey')!='undefined'&&$(this).attr('data-fbkey')!=''?$(this).attr('data-fbkey'):'';pelm.share.fb(shareVars);}else if(shareType=="twitter"){shareVars.share_type="Twitter Share";var twitterVia=typeof $(this).attr('data-twitter_via')!='undefined'&&$(this).attr('data-twitter_via')!=''?$(this).attr('data-twitter_via'):'';shareVars.twitterVia=twitterVia;pelm.share.twitter(shareVars);}else if(shareType=="gplus"){shareVars.share_type="Google+ Share";pelm.share.gplus(shareVars);}else if(shareType=="pinterest"){shareVars.share_type="Pinterest";pelm.share.pinterest(shareVars);}
if(typeof e.stopPropagation=='function'){e.preventDefault();e.stopPropagation();e.cancelBubble=true;}else{e.preventDefault();e.cancelBubble=true;}
return false;});pelm.share={};pelm.share.fb=function(sObj){var obj={method:'feed',link:sObj.url,picture:sObj.picture,name:sObj.title,caption:sObj.caption,description:sObj.description,gap_label:sObj.gap_label};var fbkey='',shareurlredirect='';if(typeof sObj.fbkey!='undefined'&&sObj.fbkey&&sObj.fbkey!=''){fbkey=sObj.fbkey;}else if(typeof window._config.fb_apikey=='string'){fbkey=window._config.fb_apikey;}else if(window._config.fb_apikey&&typeof window._config.fb_apikey[0]!=='undefined'){fbkey=window._config.fb_apikey[0];}
if(typeof window._config.share_redirect_url=='string'){shareurlredirect=window._config.share_redirect_url;}else if(window._config.share_redirect_url&&typeof window._config.share_redirect_url[0]!=='undefined'){shareurlredirect=window._config.share_redirect_url[0];}
var params='app_id='+fbkey
+'&link='+obj.link
+'&picture='+obj.picture
+'&name='+encodeURIComponent(obj.name)
+'&caption='+encodeURIComponent(obj.caption)
+'&description='+encodeURIComponent((obj.description?obj.description:obj.caption))
+'&redirect_uri='+(shareurlredirect?shareurlredirect:obj.link)
+'&display=popup';window.open('https://www.facebook.com/dialog/feed?'+params,'feedDialog','toolbar=0,status=0,width=626,height=436');dataLayer.push({'event':"eventTracker",'eventCategory':window._config.ga_product,'eventAction':'clicks','eventLabel':typeof obj.gap_label!='undefined'&&obj.gap_label!=''?obj.gap_label+' | facebook':''+"facebook"});window.pelm.track.socialShare(sObj);};pelm.share.twitter=function(sObj){var twitterMsg="";twitterMsg+=typeof sObj.title!='undefined'&&sObj.title!=''?sObj.title+" ":'';if(sObj.url.indexOf('http://')>-1){sObj.url=sObj.url.substring(7);}else if(sObj.url.indexOf('https://')>-1){sObj.url=sObj.url.substring(8);}
twitterMsg+=typeof sObj.url!='undefined'&&sObj.url!=''?"https://"+sObj.url+" ":'';twitterMsg=twitterMsg.replace('#','');sObj.url=sObj.url.replace('#','');(function(){window.twttr=window.twttr||{};var D=550,A=450,C=screen.height,B=screen.width,H=Math.round((B/2)-(D/2)),G=0,F=document,E;if(C>A){G=Math.round((C/2)-(A/2));}
var params='url='+encodeURIComponent(sObj.url)+'&text='+encodeURIComponent(twitterMsg);window.twttr.shareWin=window.open('http://twitter.com/share?'+params,'','left='+H+',top='+G+',width='+D+',height='+A+',personalbar=0,toolbar=0,scrollbars=1,resizable=1');}());dataLayer.push({'event':"eventTracker",'eventCategory':window._config.ga_product,'eventAction':'clicks','eventLabel':typeof sObj.gap_label!='undefined'&&sObj.gap_label!=''?sObj.gap_label+' | twitter':''+"twitter"});window.pelm.track.socialShare(sObj);};pelm.share.gplus=function(sObj){window.open('https://plus.google.com/share?url='+sObj.url,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');dataLayer.push({'event':"eventTracker",'eventCategory':window._config.ga_product,'eventAction':'clicks','eventLabel':typeof sObj.gap_label!='undefined'&&sObj.gap_label!=''?sObj.gap_label+' | googlePlus':''+"googlePlus"});window.pelm.track.socialShare(sObj);};pelm.share.pinterest=function(sObj){window.open('//pinterest.com/pin/create/button/?url='+sObj.url+'&media='+sObj.picture+'&description='+sObj.description,'','menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');dataLayer.push({'event':"eventTracker",'eventCategory':window._config.ga_product,'eventAction':'clicks','eventLabel':typeof sObj.gap_label!='undefined'&&sObj.gap_label!=''?sObj.gap_label+' | pinterest':''+"pinterest"});window.pelm.track.socialShare(sObj);};require(['ui'],function(ui){ui.init();});});(function($){$.fn.textfill=function(maxFontSize){maxFontSize=parseInt(maxFontSize,10);return this.each(function(){var theText=$("span",this),parent=theText.parent(),maxHeight=parent.height(),maxWidth=parent.width(),fontSize=parseInt(theText.css("fontSize"),10),multiplier=maxWidth/theText.width(),newSize=parseInt(fontSize*multiplier,10)-1;if(newSize==(maxFontSize-1))newSize=maxFontSize;theText.css("fontSize",(maxFontSize>0&&newSize>maxFontSize)?maxFontSize:newSize);});};})($);if(!window._config.awrr_report_page){$("h1").textfill(42);$("#school-address").textfill(18);window.setTimeout(function(){$("h1").textfill(42);$("#school-address").textfill(18);},500);}
if($(".takeover-news-band")[0]){document.body.className=document.body.className.replace("adalignwithbox","");}
var dfpbrtr_timestamp=unescape(_fd.k('pelm_brtr_timestamp'));if(dfpbrtr_timestamp=="undefined"||dfpbrtr_timestamp==undefined||dfpbrtr_timestamp==null||dfpbrtr_timestamp=="null"){var currenttimeinsecs=new Date().getTime()/1000;_fd.m("pelm_brtr_timestamp",currenttimeinsecs,30);}
if(typeof window._config.dfp_bt_cookie_string!=="undefined"){var dfpbrtr=unescape(_fd.ls_get("local","pelm_brtr"));if(dfpbrtr=="undefined"||dfpbrtr==null||dfpbrtr=="null"){dfpbrtr='';}
var adbrtrarray=window._config.dfp_bt_cookie_string.split("-");for(i=0;i<adbrtrarray.length;i++){if(dfpbrtr.indexOf(adbrtrarray[i])==-1){if(dfpbrtr.length>0){dfpbrtr=dfpbrtr+"-";}
dfpbrtr=dfpbrtr+adbrtrarray[i];}}
if(dfpbrtr!=""){_fd.ls_set("local","pelm_brtr",dfpbrtr);}}});