define('news-page',['jquery','session','defaults','carousels','modals','ui','showhide','takeover','modules/live_cameras','web/modules/videos/video_player'],function($,_session,defaults,carousels,modals,ui,showhide,takeover,live_cameras,player){var news_dfpad_count=1;var ads_array_sp=[];var ad_chk_count=1;var load_ad_inview=true;var Mediator={init:function(){if(typeof window._config!="undefined"&&typeof window._config.news_webview!="undefined"&&window._config.news_webview==true){var viewpost_width=$(window).width();if(viewpost_width<=641){carousels.bind('#photo-gallery',{displaySlideQty:8,moveSlideQty:4,touchEnabled:true,oneToOneTouch:true});carousels.bind('#photo-gallery-slider',{displaySlideQty:8,moveSlideQty:4,touchEnabled:true,oneToOneTouch:true});}else{carousels.bind('#photo-gallery',{displaySlideQty:8,moveSlideQty:7,touchEnabled:true,oneToOneTouch:true});carousels.bind('#photo-gallery-slider',{displaySlideQty:8,moveSlideQty:7,touchEnabled:true,oneToOneTouch:true});}}
$(document).ready(function(){if($("#video_player").length>0){player.init();}});window.addEventListener('load',function(){var mob_touch=document.getElementById('logic_mobile_touch');if(typeof mob_touch!="undefined"&&mob_touch!=null){mob_touch.addEventListener('touchstart',function(e){if(typeof e.target.id=='undefined'||e.target.id==null||e.target.id==""){}else{if(e.target!==e.currentTarget){var clickedItem=e.target.id;var tfmurl=$('#'+e.target.id).attr("data-fmimg");$('#main_news_image').attr("src",tfmurl);}
e.preventDefault();e.stopPropagation();}},false);mob_touch.addEventListener('touchmove',function(e){if(typeof e.target.id=='undefined'||e.target.id==null||e.target.id==""){}else{e.preventDefault();}},false);mob_touch.addEventListener('touchend',function(e){if(typeof e.target.id=='undefined'||e.target.id==null||e.target.id==""){}else{e.preventDefault();}},false);}},false);$(function(){var news_url=pelm_url.removeUrlTracking(window.location.href);if(news_url.indexOf("date")>0){$(".tab-navigation .date").addClass('active expanded');$("#month-subnav").show();var url_parts=news_url.split('/');var select_month="";var select_year="";for(var p=0;p<url_parts.length;p++){if(url_parts[p].toLowerCase()=='date'){select_year=url_parts[p+1];select_month=url_parts[p+2];break;}}
if(select_month!=""){$("#ddlmonth").val(select_month);}
if(select_year!=""){$("#ddlyear").val(select_year);}
$("#month-subnav").find('select').uniform();}else{$(".tab-navigation .category").addClass('active expanded');$("#category-subnav").show();}
$('#news-landing .has-subnav a, #news-article .has-subnav a').on('click',function(event){event.preventDefault();$('#news-landing .tab-navigation li, #news-article .tab-navigation li').removeClass('active');$(this).parent().addClass('active');var parentElm=$(this).parent();if($(this).parent().hasClass("expanded")){$(this).parent().removeClass('expanded').addClass('collapsed');$target=$($(this).attr("href"));$target.hide();}else{$('#news-landing .subnav, #news-article .subnav').hide();$('#news-landing .has-subnav, #news-article .has-subnav').removeClass('expanded');$(this).parent().removeClass('collapsed').addClass('expanded');$target=$($(this).attr("href"));$target.show();$target.find('select').uniform();}});if($("#video-carousel").length>0){var c_options={};c_options={displaySlideQty:3,moveSlideQty:3,infiniteLoop:false,hideControlOnEnd:true};if(typeof $("#video-carousel").slider!=='function'||!$("#video-carousel").parent().hasClass('bx-window')){carousels.bind("#video-carousel",c_options);$('.video_specs_module .bx-wrapper').css({'width':'700px'});$('.video_specs_module .bx-wrapper').css({'width':'728px'});$('.video_specs_module .bx-window').css({'width':'688px'});$('#video-carousel .videoitems').css({'width':'216px'});}}
if(window._config.autofile_url!==undefined&&window._config.autofile_url!==null){$("head").append("<link rel='canonical' href='http://"+window._config.autofile_url+"'>");}
$('#news-room_archive #ddlyear').on('change',function(e){var val=$(this).val(),url='',f;if(!isNaN(val)){require(['localization/copy'],function(copy){url=copy.page_url.url_news_releases;});if(url){url=url+'/date/'+val;f=$(this).closest('form');f.attr('action',url);f.submit();}}});if(typeof window._config.news_dfpad_count!='undefined'){news_dfpad_count=window._config.news_dfpad_count;for(var k=0;k<news_dfpad_count;k++)
{var slot_name='div-dfp-ad-news-page-'+(k+1);ads_array_sp[k]=slot_name;}}
if(typeof window._config.news_page_ad_account!='undefined'){news_page_ad_account=window._config.news_page_ad_account;}
if(typeof window._config.load_ad_inview!='undefined'){load_ad_inview=window._config.load_ad_inview;}
loadad=function(eln){googletag.cmd.push(function(){var slot_name=eln;var slot=googletag.defineSlot(news_page_ad_account,[[300,250],[300,253]],slot_name).setTargeting('pos','bottom').addService(googletag.pubads());googletag.display(slot_name);});};if(load_ad_inview==true&&typeof ads_array_sp!='undefined'&&ads_array_sp.length>0){for(var k=0;k<ads_array_sp.length;k++){if(typeof ads_array_sp[k]!="undefined"){var el_name=ads_array_sp[k].trim();el=document.getElementById(el_name);if(typeof el!='undefined'){loadad(el_name);}}}}
checkadsize=function(offsetHeight){if(offsetHeight==250&&ad_chk_count<=5){ad_chk_count++;setTimeout(function(){var bbadel=document.getElementById('div-dfp-ad-news-page-bigbox');var newh=bbadel.offsetHeight;if(newh==600){$('#dfp_ad_helper').hide();bbadel.className+=bbadel.className?' ad-billboard600':'ad-billboard600';$('.clear-right').css('clear','both');return;}
checkadsize(newh);},500);}};var bigboxaddiv=document.getElementById('div-dfp-ad-news-page-bigbox');loadbigboxad=function(){if(typeof bigboxaddiv!="undefined"&&bigboxaddiv!=null){if(typeof window._config.news_page_ad_account=='undefined'){setTimeout(function(){loadbigboxad();},500);}
else{googletag.cmd.push(function(){var slot_name="div-dfp-ad-news-page-bigbox";var slot=googletag.defineSlot(window._config.news_page_ad_account,[[300,250],[300,600]],slot_name).setTargeting('pos','top').addService(googletag.pubads());googletag.display(slot_name);});var bigboxadh=bigboxaddiv.offsetHeight;checkadsize(bigboxadh);};}};loadbigboxad();if(typeof dataLayer!=='undefined'){var gapNewsTitle="";for(var i=0;i<dataLayer.length;i++){if(typeof dataLayer[i].newsTitle!="undefined"){gapNewsTitle=dataLayer[i].newsTitle;break;}}
if($('#news-article').length){var platformName="web";if(typeof window.url_page!=="undefined"&&window.url_page['url'].indexOf('webview')!=-1){platformName="webview";}
dataLayer.push({'event':"eventTracker",'eventCategory':'news','eventAction':'viewsPlatforms','eventLabel':gapNewsTitle+" | "+platformName});}
$('#searchform_news').on('submit',function(e){dataLayer.push({'event':"eventTracker",'eventCategory':'news','eventAction':'clicks','eventLabel':"findYourForecast"});});$('.news-article .social-share .share_fb').click(function(){dataLayer.push({'event':"eventTracker",'eventCategory':'news','eventAction':'clicks','eventLabel':"shareNews | "+gapNewsTitle+" | share_fb"});});$('.news-article .social-share .share_gplus').click(function(){dataLayer.push({'event':"eventTracker",'eventCategory':'news','eventAction':'clicks','eventLabel':"shareNews | "+gapNewsTitle+" | share_gplus"});});$('.news-article .social-share .share_twitter').click(function(){dataLayer.push({'event':"eventTracker",'eventCategory':'news','eventAction':'clicks','eventLabel':"shareNews | "+gapNewsTitle+" | share_twitter"});});}});}};Mediator.init();});function SubmitMonthForm(url,ly,lm,ld){var d=new Date();var f=document.getElementById("newsMonthForm");var u=url+ld+'/';var y=f.ddlyear.value;var m=f.ddlmonth.value;var cm=f.ddlmonth[d.getMonth()+1].value;if(y==''||y==ly){y=new Date().getFullYear();}
if(m==''||m==lm){m=cm;}
window.location=u+y+'/'+m+'/';}
function loadNewsImage(url){$('#main_news_image').attr("src",url);}
function getParameterByName(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regex=new RegExp("[\\?&]"+name+"=([^&#]*)"),results=regex.exec(location.search);return results===null?"":decodeURIComponent(results[1].replace(/\+/g," "));};require(['news-page']);