define(['module.base'],function(Module){Module.PelmVideoEvents=function(){var self=this;var eventLabel,eventNames,eventsToTrack,playTracked=false,startTracked=false,endTracked=false,pauseEndTracked=false,pauseTracked=false,listVideoComplete=false,listVideoStartTracked=false,playlistMenuBind=false,impressionCount=0,players=[],videoInterval
autoStartTracked=1,autoStartTrackedList=false,loadTrackingDone=false,videoImpressionList=[];isInAdState=function(player){var adStateRegex=/(\s|^)vjs-ad-(playing|loading)(\s|$)/;return adStateRegex.test(player.el().className);};var player_options;eventNames={"video_load":"videoLoaded","start":"videoClickPlay","auto_start":"videoAutoPlay","play":"videoPlayPause","pause":"videoClickPause","fullscreen_exit":"exitFullScreen","fullscreen_enter":"openFullScreen","end":"videoComplete","open_video_playlist":"openVideoPlaylist"};var registerEventListeners=function(pelm_player){pelm_player.on('contentplayback',function(evt){var player=this;if(player.playlist().length>0&&Math.round(player.currentTime())==0){if(!listVideoComplete){if(Math.round(player.currentTime())!=Math.round(player.duration())&&!listVideoStartTracked){if(!autoStartTrackedList){if(player.autoplay()){sendGapTracking(getEventName('auto_start'),player.autoplay());}else{sendGapTracking(getEventName('start'),false);}
autoStartTrackedList=true;}
listVideoStartTracked=true;}}}else{if(Math.round(player.currentTime())==0&&!startTracked){if(player.autoplay()&&autoStartTracked==1){sendGapTracking(getEventName('auto_start'),player.autoplay());autoStartTracked+=1;}else{sendGapTracking(getEventName('start'),false);}
startTracked=true;}}});pelm_player.on('play',function(){var player=this;eventLabel=getEventLabel(player);pauseTracked=false;if(player.playlist().length>0)
{if(Math.round(player.currentTime())==0&&!listVideoComplete)
{if(Math.round(player.currentTime())!=Math.round(player.duration())&&!listVideoStartTracked)
{if(player.autoplay()&&!autoStartTrackedList){sendGapTracking(getEventName('auto_start'),player.autoplay());autoStartTrackedList=true;}else{sendGapTracking(getEventName('start'),false);}
listVideoStartTracked=true;}}}
else
{if(Math.round(player.currentTime())==0&&!startTracked)
{if(player.autoplay()&&autoStartTracked==1){sendGapTracking(getEventName('auto_start'),player.autoplay());autoStartTracked+=1;}else{sendGapTracking(getEventName('start'),false);}
startTracked=true;}}
if(!playTracked&&startTracked&&Math.round(player.currentTime())>0){if(!isInAdState(player)){sendGapTracking(getEventName('play'),false);playTracked=true;}}});pelm_player.on('pause',function(){var player=this;eventLabel=getEventLabel(player);if(Math.round(player.duration())!==Math.round(player.currentTime())&&Math.round(player.currentTime())!==0){sendGapTracking(getEventName('pause'),false);}
playTracked=false;pelm_player.one('play',function(){var player=this;pauseTracked=false;pauseEndTracked=false;if(player.playlist().length===0&&Math.round(player.currentTime())===0&&!startTracked){if(player.autoplay()&&autoStartTracked==1){sendGapTracking(getEventName('auto_start'),player.autoplay());autoStartTracked+=1;}else{sendGapTracking(getEventName('start'),false);}
startTracked=true;}
if(!playTracked&&Math.round(player.currentTime())>0){if(!isInAdState(player)){sendGapTracking(getEventName('play'),false);playTracked=true;}}});});pelm_player.on('loadedmetadata',function(){var player=this;eventLabel=getEventLabel(player);endTracked=false;if(typeof player.playlistMenu!='undefined'&&typeof player.playlistMenu.items!='undefined'&&player.playlistMenu.items.length>0&&playlistMenuBind==false){for(var x=0;x<player.playlistMenu.items.length;x++){player.playlistMenu.items[x].on('click',function(){sendGapTracking(getEventName('open_video_playlist'),false,this.item.name);})}
playlistMenuBind=true;}
if(player.playlist().length>0){if(videoImpressionList.indexOf(player.mediainfo.id)<0){sendGapTracking(getEventName('video_load'),true);if(typeof window._config.news_webview!='undefined'&&window._config.news_webview!=""){var platform_webview=(window._config.platform_webview)?window._config.platform_webview:window._config.platform;}
videoImpressionList[impressionCount]=player.mediainfo.id;impressionCount++;}
listVideoComplete=false;listVideoStartTracked=false;}
else
{if(!loadTrackingDone){sendGapTracking(getEventName('video_load'),true);if(typeof window._config.news_webview!='undefined'&&window._config.news_webview!=""){var platform_webview=(window._config.platform_webview)?window._config.platform_webview:window._config.platform;}
loadTrackingDone=true;}}});pelm_player.on('fullscreenchange',function(){var player=this;if(player.isFullscreen()){sendGapTracking(getEventName('fullscreen_enter'),false);}else{sendGapTracking(getEventName('fullscreen_exit'),false);}});pelm_player.on('contentended',function(){autoStartTrackedList=false;if(!endTracked&&!pauseEndTracked){sendGapTracking(getEventName('end'),true);endTracked=true;startTracked=false;listVideoComplete=true;}});pelm_player.on('ended',function(evt){var player=this;autoStartTrackedList=false;if((pelm_player.duration()-pelm_player.currentTime())>3&&(window._config&&window._config.platform=="mobile")){evt.preventDefault();return;}
try{this.trigger('adtimeout');}catch(e){console.log(e);}});pelm_player.on('loadstart',function(e){self.pelmVideoPlayer.updateAdRequest(this);});pelm_player.on('loadeddata',function(e){self.pelmVideoPlayer.checkMediaReady(this);});pelm_player.on('adend',function(evt){self.pelmVideoPlayer.showPageAds(evt);});pelm_player.on('adstart',function(){self.pelmVideoPlayer.hidePageAds();this.bigPlayButton.hide();});pelm_player.on('ads-click',function(){self.pelmVideoPlayer.pauseAd(this.id());});pelm_player.on('ima3-ad-error',function(evt){self.pelmVideoPlayer.showPageAds(evt);if(pelm_player.paused()){pelm_player.play();}});};if(typeof videojs!='undefined'){videojs.registerPlugin('pelmEvents',function(options){initPlayer(this,options);});var initPlayer=function(pl,options){var pelm_player=pl,playlistId,videoId,disableAd,adRequestMode;if(typeof options!=='undefined'){videoId=(typeof options.videoId!='undefined')?options.videoId:'';playlistId=(typeof options.playlistId!='undefined')?options.playlistId:'';adRequestMode=(typeof options.adRequestMode!='undefined')?options.adRequestMode:adRequestMode;disableAd=shouldDisableAd(options.adProduct);}
player_options=options;registerEventListeners(pelm_player);pelm_player.ready(function(){var player=this;if(typeof player.ima3!=='undefined'){player.ima3.settings.serverUrl=encodeAdUrl(getPrerollAdParams(options));if(adRequestMode){player.ima3.settings.requestMode=adRequestMode;}
if(disableAd===true){self.pelmVideoPlayer.disablePlayerAds(player);}}
players.push(player);if(playlistId){self.pelmVideoPlayer.updatePlaylist(player,videoId,playlistId,options);}});};}
var getEventLabel=function(player){if(player.mediainfo&&player.mediainfo.id){eventLabel=player.mediainfo.name;}else{eventLabel=player.currentSrc().split("/").slice(-1)[0].replace(/\.(\w{3,4})(\?.*)?$/i,'');}
return eventLabel;};var encodeAdUrl=function(adParams){var adUrl='https://pubads.g.doubleclick.net/gampad/ads?';if(typeof window.npa!=="undefined"){adUrl+=window.npa+'&';}
Object.keys(adParams).forEach(function(k){if((k=="ciu_szs")&&((typeof window._config.platform!=="undefined"&&window._config.platform=="mobile")||(typeof window._config.newsid!=="undefined"))){}else{adUrl+=k+'='+adParams[k]+'&';}});return adUrl.slice(0,-1);};var getEventName=function(name){if(eventNames[name]){return eventNames[name];}
return name;};var sendGapTracking=function(action,event_non_int,evtLbl){if(typeof dataLayer!='undefined'){dataLayer.push({'videoAction':action,'videoLabel':(evtLbl)?evtLbl:eventLabel,'videoPlatform':getPlatformName(window._config),'eventNonInt':event_non_int,'event':'videoEvent'});}};var getPlatformName=function(windowConfig){var video_platform='';if(typeof windowConfig.news_webview!='undefined'&&windowConfig.news_webview!=""){var platform_webview=(windowConfig.platform_webview)?windowConfig.platform_webview:windowConfig.platform;video_platform='webview | '+platform_webview;}else{if(typeof windowConfig.platform!='undefined'&&windowConfig.platform=='web'){video_platform='desktopWeb';}else if(typeof windowConfig.platform!='undefined'&&windowConfig.platform=='mobile'){video_platform='mobileWeb';}}
return video_platform;}
var getOptionValue=function(options,key,defaultValue){return(typeof options[key]!="undefined"&&options[key]!="")?options[key]:defaultValue;};var shouldDisableAd=function(adProduct){return adProduct.indexOf("disableads")!=-1;};var disablePlayerAds=function(player){player.ima3.settings.serverUrl='';player.ima3.settings.hardTimeouts=true;player.trigger('adtimeout');};var getPrerollAdParams=function(options){return{"sz":getOptionValue(options,"adSz","640x480"),"ciu_szs":getOptionValue(options,"adCiuSzs","728x90"),"iu":getOptionValue(options,"adProduct",""),"gdfp_req":"1","env":"vp","output":"xml_vast3","unviewed_position_start":"1","url":"[referrer_url]","correlator":"[timestamp]","cust_params":getOptionValue(options,"adParams","")};};self.pelmVideoPlayer={updatePlaylist:function(player,videoId,playlistId,options){var index=0,isautoplay=false,cPlaylistId=null,playVid=(typeof options.autoplay!='undefined')?options.autoplay:false;if(playlistId){player.catalog.getPlaylist(playlistId,function(error,playlist){if(playlist){player.catalog.load(playlist);player.playlist.autoadvance(0);self.pelmVideoPlayer.setCurrentVideo(player,videoId,playVid);}});}},setCurrentVideo:function(player,videoId,playVideo){var index=0,vidId=videoId||'';var plist=player.playlist();var itr=0;if(plist){for(var j in plist){if(plist[j].id==vidId){index=j;break;}}
player.playlist.currentItem(parseInt(index));if(videoId&&playVideo){window.setTimeout(function(){player.play();},1000);}
return parseInt(index);}else if(itr++<10){window.setTimeout(self.pelmVideoPlayer.setCurrentVideo,100);}},updateAdRequest:function(player){player_options.adParams=self.pelmVideoPlayer.setPartnerName(player.mediainfo,player_options.adParams);player.ima3.settings.serverUrl=encodeAdUrl(getPrerollAdParams(player_options));},setPartnerName:function(mediainfo,adParams){var partnerName='';adParams=adParams.replace(/\%26videoid=[^%]*/,"%26videoid="+mediainfo.id);for(let tagIndex=0;tagIndex<mediainfo.tags.length;++tagIndex){if(mediainfo.tags[tagIndex].indexOf("_partnership")>-1){partnerName=mediainfo.tags[tagIndex].split("_partnership")[0];}else if(mediainfo.tags[tagIndex].indexOf("corus")>-1){partnerName=mediainfo.tags[tagIndex];}}
if(partnerName){if(adParams.indexOf("video_partner")>-1){adParams=adParams.replace(/\%26video_partner=[^%]*/,"%26video_partner="+partnerName);}else{adParams+="%26video_partner="+partnerName;}}else{if(adParams.indexOf("video_partner")>-1){adParams=adParams.replace(/\%26video_partner=[^%]*/,"");}}
return adParams;},checkMediaReady:function(player){if(player.mediainfo){self.pelmVideoPlayer.processMetadataDisplay(player,player_options);if(typeof window._config!=="undefined"&&typeof window._config.video_gallery!=="undefined"){self.pelmVideoPlayer.updateShareLink(player);}
itr=0;}
else if(itr++<10){window.setTimeout(self.pelmVideoPlayer.checkMediaReady,100);}},processMetadataDisplay:function(player,options){var pretitle,thumbPosition,namePosition,sdescPosition,ldescPosition,minfo=player.mediainfo,fc=player.el(),topMetadata=false,bottomMetadata=false,h2=document.createElement('h2'),sdesc=document.createElement('p'),ldesc=document.createElement('p'),tdiv=document.createElement('div'),bdiv=document.createElement('div');tdiv.className='pelm-head top-meta',bdiv.className='pelm-description bottom-meta';sdesc.className='pelm-short-description';pretitle=(typeof options.preTitle!=='undefined')?options.preTitle:'';thumbPosition=(typeof options.thumbnailPosition!='undefined')?options.thumbnailPosition:'';namePosition=(typeof options.metadataDisplay!='undefined'&&typeof options.metadataDisplay.name!='undefined')?options.metadataDisplay.name:'';sdescPosition=(typeof options.metadataDisplay!='undefined'&&typeof options.metadataDisplay.shortDescription!='undefined')?options.metadataDisplay.shortDescription:'';ldescPosition=(typeof options.metadataDisplay!='undefined'&&typeof options.metadataDisplay.longDescription!='undefined')?options.metadataDisplay.longDescription:'';if(!minfo){return false;}
if(namePosition&&namePosition.indexOf('none')<0){h2.innerHTML=pretitle+minfo.name;if(namePosition.indexOf('top')>-1){tdiv.appendChild(h2);topMetadata=true;}else if(namePosition.indexOf('bottom')>-1){bdiv.appendChild(h2);bottomMetadata=true;}}
if(sdescPosition&&sdescPosition.indexOf('none')<0){sdesc.innerHTML=(minfo.description)?minfo.description:minfo.name;if(sdescPosition.indexOf('top')>-1){tdiv.appendChild(sdesc);topMetadata=true;}else if(sdescPosition.indexOf('bottom')>-1){bdiv.appendChild(sdesc);bottomMetadata=true;}}
if(ldescPosition&&ldescPosition.indexOf('none')<0){ldesc.innerHTML=(minfo.long_description)?minfo.long_description:'';if(ldescPosition.indexOf('top')>-1){tdiv.appendChild(ldesc);topMetadata=true;}else if(ldescPosition.indexOf('bottom')>-1){bdiv.appendChild(ldesc);bottomMetadata=true;}}
if(topMetadata){if(document.getElementsByClassName('pelm-head').length>0){document.getElementsByClassName('pelm-head')[0].innerHTML=tdiv.innerHTML;}else{if(!document.documentElement.classList.contains("mobile")){player.el().parentNode.insertBefore(tdiv,fc);}}}},updateShareLink:function(player){var minfo=player.mediainfo;var pageUrl=(typeof window._config!=="undefined"&&window._config.video_share_url!=='undefined')?window._config.video_share_url:'',videoId=minfo.id,videoTitle=(minfo.name).replace(/[^a-z A-Z0-9]+/g,"").toLowerCase().replace(/ /g,"-"),shareUrl='',shareTitle='sharevideo',opt={};if(typeof window._config!=="undefined"&&typeof window._config.video_gallery!=="undefined"){shareUrl=(pageUrl)?pageUrl+videoTitle+'/'+shareTitle+'/'+videoId:getPageUr();if(typeof window._config.videocat!=="undefined"){shareUrl+="/"+window._config.videocat;}
opt={"url":shareUrl,"title":videoTitle,"description":(minfo.description)?minfo.description:minfo.name,"deepLinking":true};player.social(opt);window.history.pushState('Object',videoTitle,shareUrl);}},showPageAds:function(evt){if(typeof window._config!=="undefined"&&typeof window._config.video_gallery!=="undefined"){$("#div-gpt-ad-companion").empty();$("#div-gpt-ad-companion").hide();$("#div-gpt-ad-topbanner").show();if(window.firstvideoplayed){if(typeof console!='undefined'){console.log("***googletag.pubads().refresh - pelm_video_events.js - 2** -",[window.adslots['div-gpt-ad-topbanner']]);}
if(googletag){googletag.display("div-gpt-ad-topbanner");window.firstvideoplayed=false;}}else{if(googletag){googletag.pubads().refresh([window.adslots['div-gpt-ad-topbanner']]);}}
if(typeof console!='undefined'){console.log("***googletag.pubads().refresh - pelm_video_events.js - 3** -",[window.adslots['div-gpt-ad-topbanner']]);}}},hidePageAds:function(){if(typeof window._config!=="undefined"&&typeof window._config.video_gallery!=="undefined"){$("#div-gpt-ad-topbanner").empty();$("#div-gpt-ad-topbanner").hide();}},pauseAd:function(targetPlayer){var id=targetPlayer;if(typeof videojs=='function'&&typeof videojs(id).ima3!=='undefined'&&videojs(id).ima3.adsManager&&typeof videojs(id).ima3.adPlayer!=='undefined'){var adp=videojs(id).ima3.adPlayer;if(adp.hasOwnProperty('pause')){if(adp.paused()==false){adp.pause();}}}},clearVideoInterval:function(){if(videoInterval){clearInterval(videoInterval);}},pauseVideo:function(targetPlayer){var id=targetPlayer,p=videojs(id);if(p.paused()==false){self.pelmVideoPlayer.clearVideoInterval();p.pause();}},disposePlayer:function(player){self.pelmVideoPlayer.pauseAd(player.id());self.pelmVideoPlayer.pauseVideo(player.id());if(player.ended()==false){player.trigger('ended');}
self.pelmVideoPlayer.clearVideoInterval();setTimeout(function(){player.dispose();},0);},discardPlayer:function(playerName){if(typeof videojs!='function'){return false;}
for(var i=0;i<players.length;i++){if(players[i].id()==playerName){self.pelmVideoPlayer.disposePlayer(videojs(players[i].id()));players.splice(i,1);}}},pauseAllVideos:function(){pauseTracked=true;if(typeof videojs!='function'){return false;}
for(var i=0;i<players.length;i++){self.pelmVideoPlayer.pauseVideo(players[i].id());self.pelmVideoPlayer.pauseAd(players[i].id());}},pauseVideo:function(targetPlayer){var id=targetPlayer,p=videojs(id);if(p.paused()==false){self.pelmVideoPlayer.clearVideoInterval();p.pause();}},getPrerollAdParams:getPrerollAdParams,disablePlayerAds:disablePlayerAds,shouldDisableAd:shouldDisableAd,registerEventListeners:registerEventListeners,getEventName:getEventName,getEventLabel:getEventLabel,getPlatformName:getPlatformName};};return Module.factory('PelmVideoEvents');});;