define(['jquery','jquery.scroller','localization/copy','carousels'],function($,__scroller,copy,carousels){var alert_referer=null;var ch_options_alerts={displaySlideQty:2,moveSlideQty:2,infiniteLoop:false,hideControlOnEnd:true,};window.fixAlertInEffectSlider=function(){if(typeof $("#master-alert").slider!=='function'||!$("#master-alert").parent().hasClass('bx-window')){carousels.bind("#master-alert",ch_options_alerts);$('#master-alert').removeClass('visuallyhidden');setTimeout(fixAlertInEffectSlider,1000);}};function insertCount(slide_curr,slide_count){$('#slide-counter').html('<strong>'+(slide_curr+1)+'</strong> of '+slide_count);};var slider=null;if($&&$.bxSlider){slider=$('#master-alert').bxSlider({displaySlideQty:2,moveSlideQty:2,infiniteLoop:false,hideControlOnEnd:true,pager:false,nextText:'<i class="icon-chevron-right"></i>',prevText:'<i class="icon-chevron-left"></i>',onSliderLoad:function(element){if(slider&&typeof slider.getSlideCount=='function'){var slide_count=slider.getSlideCount();var slide_curr=slider.getCurrentSlide();insertCount(slide_curr,slide_count);}},onNextSlide:function(element){if(slider&&typeof slider.getSlideCount=='function'){var slide_count=slider.getSlideCount();var slide_curr=slider.getCurrentSlide();insertCount(slide_curr,slide_count);}},onPrevSlide:function(element){if(slider&&typeof slider.getSlideCount=='function'){var slide_count=slider.getSlideCount();var slide_curr=slider.getCurrentSlide();insertCount(slide_curr,slide_count);}}});}
function setAlertClosed(elements){var alertIds=AlertData(),closed_ids=getCookie('closed_takeover_alerts'),id_list="";if(closed_ids!=null){closed_ids=decodeURIComponent(closed_ids);closed_ids.replace('"',"");id_list=closed_ids+","+alertIds;}
else{id_list=alertIds;}
setCookie('closed_takeover_alerts',id_list,1);}
function userHasClosed(elements){return false;}
function takeover(elements){setAlertClosed(elements);alert_referer=getCookie('alert_referer');if(userHasClosed(elements)){return false;}else{var placecode=window._config.placecode;if(!placecode){placecode=AlertPlaceCode();}
$('body').addClass('bg-takeover');if(IsTakeOverPage())
{var location_name=window._config.city_name+','+window._config.prov_code,location_url='/weather/';if(copy&&typeof copy.page_url!='undefined'&&typeof copy.page_url.weather_url!='undefined'){location_url='/'+copy.page_url.weather_url+'/';}
if(typeof window._uf!='undefined'&&typeof window._uf.u!='undefined'){location_url+=window._uf.u+'/';}else{location_url+=placecode+'/';}
if(typeof window._uf!='undefined'&&typeof window._uf.c!='undefined'){location_url='/'+window._uf.c+location_url;}
if(typeof window.postalcode!='undefined'){location_url+=window.postalcode+'/';}
if(typeof window.gridindex!='undefined'){location_url+=window.gridindex+'/';}
location_url=location_url.replace(/\/$/,"");var date=new Date();location_url+=(location_url.indexOf('?')==-1?'?':'&')+'no_alert_redirect='+date.getFullYear()+'-'+(date.getMonth()+1)+'-'+date.getDate();if(typeof window._config.city_name!="undefined"&&window._config.city_name!=""&&typeof window._config.prov_code!="undefined"&&window._config.prov_code!=""){$('<div class="alertBand"><a class="alert-ineffect-text" href="'+location_url+'">'+location_name+'</a><div class="alert-ineffect-text"><i class="icon-play"></i>'+copy.takeover.alertineffect+'</div><a class="alert-text" href="'+location_url+'">'+copy.takeover.alertviewforecast+'<i class="icon-play"></i></a></div>').insertBefore('#main-content');}else{$('<div class="alertBand"><a class="alert-ineffect-text" href="/'+window._config.lbl_alerts+'/ca/">'+copy.takeover.alertindex+'</a><div class="alert-ineffect-text"><i class="icon-play"></i>'+copy.takeover.alertineffect+'</div><a class="close-icon hidetext">Close</a><div class="alert-text">'+copy.takeover.close+'</div></div>').insertBefore('#main-content');}
$('#masthead').insertBefore('.alertBand');$('.alertBand .close-icon').on('click',function(event){$('body').removeClass('bg-takeover');$('.alertBand').fadeOut('slow',function(){$(this).remove();});$('#alert-columns').removeClass('column-container column-2').find('#alert-details').hide();document.cookie='alert_referer=; path=/';if(alert_referer!=null&&alert_referer!=""){window.location=alert_referer;}else{if(window.history.length===1){var newUrl=pelm_url.removeUrlTracking(window.location.href);var params=newUrl.split("alerts/high-alert/");window.location=(typeof _config.url_weather!="undefined"?'/'+_config.url_weather+'/':'/weather/')+params[1];}else{window.history.back();}}});}}}
function bindAlertsSavedLocation(elements){$(elements.alertIcon).on('mouseenter',function(event){var alertBand=$($(this).attr("href"));alertBand.show().position({my:"right top",at:"right top",of:$(this)});alertBand.find(elements.alertTicker).SetScroller({velocity:60,direction:'horizontal',startfrom:'right',loop:'infinite',movetype:'linear',onmouseover:'play',onmouseout:'play',onstartup:'play',cursor:'default'});});$(elements.alertBand).on('mouseleave',function(event){$(this).hide();});}
function getCookie(c_name)
{var i,x,y="",ARRcookies=document.cookie.split(";");for(i=0;i<ARRcookies.length;i++)
{x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("="));x=x.replace(' ','');if(x==c_name)
{y=ARRcookies[i].substr(ARRcookies[i].indexOf("=")+1);}}
return y;}
function setCookie(c_name,value,exdays)
{var exdate=new Date();exdate.setDate(exdate.getDate()+exdays);var c_value=escape(value)+((exdays==null)?"":";path=/; expires="+exdate.toUTCString());document.cookie=c_name+"="+c_value;}
return{init:takeover,bindAlertsSavedLocation:bindAlertsSavedLocation};});;